project:
  type: book
  execute-dir: project

book:
  title: "hebstr-book : Example Book"
  author: "hebstr"
  date: last-modified
  repo-url: https://github.com/hebstr/quarto-hebstr-book/
  chapters:
    - index.qmd
    - part: "Chapters"
      chapters:
        - chapters/01-typography.qmd
        - chapters/02-code-data.qmd
        - chapters/03-callouts-refs.qmd
    - part: "Annexes"
      chapters:
        - chapters/A1-session.qmd

format:
  hebstr-book-html: default
